import io
import json
import unittest
from unittest.mock import patch
from openpyxl import Workbook
import test_workspace as workspace
from app.ai.providers.openai_compatible import OpenAICompatibleProvider
from app.schemas.usage import ChatResult, TokenUsage


class TalentConversationTests(unittest.TestCase):
    setUp = workspace.WorkspaceTests.setUp
    tearDown = workspace.WorkspaceTests.tearDown
    base = workspace.WorkspaceTests.base

    def roster(self):
        base = self.base()
        book = Workbook()
        sheet = book.active
        sheet.append(['姓名', '当前机构', '领域', 'OpenAlex h-index'])
        for i in range(35):
            sheet.append([f'人才{i + 1}', '清华大学', '具身智能' if i >= 30 else 'AI4S', 80 - i if i < 8 else None])
        output = io.BytesIO()
        book.save(output)
        book.close()
        response = self.client.post(f'/api/knowledge/bases/{base}/upload', files={
            'file': ('人才.xlsx', output.getvalue(), 'application/octet-stream')})
        self.assertEqual(response.status_code, 201, response.text)
        return base

    def chat(self, config, messages, model, key):
        prompt = messages[0].content
        if prompt.startswith('你只负责'):
            current = messages[-1].content
            query = '清华大学人才'
            if '具身智能' in current:
                self.assertIn('上一次查询状态', prompt)
                query += '，具身智能领域'
            if '取消排序' not in current:
                query += '，按OpenAlex h-index降序'
            result = {'query': query}
        elif prompt.startswith('先识别用户任务'):
            query = json.loads(messages[-1].content)['question']
            filters = [{'field': '当前机构', 'op': 'contains', 'value': '清华大学'}]
            if '具身智能' in query:
                filters.append({'field': '领域', 'op': 'contains', 'value': '具身智能'})
            result = {'filters': filters, 'sort_by': 'OpenAlex h-index' if 'OpenAlex' in query else None,
                      'descending': True, 'limit': 20}
        else:
            self.fail('Personnel tables must not be generated by a language model')
        return ChatResult(content=json.dumps(result), usage=TokenUsage())

    def test_full_conversation_paginates_without_repeating_or_inventing_people(self):
        base = self.roster()
        history = []
        with patch.object(OpenAICompatibleProvider, 'chat', side_effect=self.chat) as model, \
             patch('app.api.routes.knowledge.EmbeddingClient') as embedding:
            def ask(question, base_id=base):
                response = self.client.post('/api/knowledge/ask', json={
                    'question': question, 'knowledge_base_id': base_id, 'history': history, 'top_k': 1})
                self.assertEqual(response.status_code, 200, response.text)
                result = response.json()
                history.append({'question': question, 'answer': result['answer'], 'query_state': result['query_state']})
                return result
            first = ask('提取清华大学相关人才')
            self.assertEqual(len(first['row_sources']), 5)
            self.assertNotIn('可排序', first['answer'])
            self.assertNotIn('无缺失', first['answer'])
            ranked = ask('按照 OpenAlex h-index 排序')
            self.assertIn('其中 8 条有', ranked['answer'])
            self.assertIn('27 条缺少', ranked['answer'])
            before = model.call_count
            second = ask('继续')
            self.assertEqual(model.call_count, before)
            self.assertEqual([r['fields']['姓名'] for r in second['row_sources']], ['人才6', '人才7', '人才8'])
            self.assertIn('第 6—8 条', second['answer'])
            self.assertFalse(second['query_state']['has_more'])
            last = ask('继续')
            self.assertEqual(last['row_sources'], [])
            self.assertIn('没有下一页', last['answer'])
            narrowed = ask('提取具身智能领域的')
            self.assertEqual(len(narrowed['row_sources']), 5)
            self.assertIn('不做排名', narrowed['answer'])
            self.assertEqual(narrowed['query_state']['offset'], 0)
            self.assertTrue(all(r['fields']['领域'] == '具身智能' for r in narrowed['row_sources']))
            for result in [first, ranked, second, last, narrowed]:
                self.assertNotIn('rankable_records', result['answer'])
                self.assertNotIn('missing_sort_values', result['answer'])
                self.assertNotIn('(Record 6)', result['answer'])
            cancelled = ask('取消排序，查看清华大学全部人才')
            self.assertIsNone(cancelled['query_state']['plan']['sort_by'])
            self.assertEqual(cancelled['query_state']['offset'], 0)
            self.assertNotIn('不参与排名', cancelled['answer'])
            embedding.assert_not_called()
            other = ask('继续', self.base('其他库'))
            self.assertIsNone(other['query_state'])
            self.assertEqual(other['row_sources'], [])

    def test_streamed_page_survives_serialized_history(self):
        base = self.roster()
        with patch.object(OpenAICompatibleProvider, 'chat', side_effect=self.chat):
            first = self.client.post('/api/knowledge/ask', json={
                'question': '清华大学人才，按OpenAlex h-index降序', 'knowledge_base_id': base}).json()
        with patch.object(OpenAICompatibleProvider, 'chat') as model, \
             patch.object(OpenAICompatibleProvider, 'stream_chat') as stream:
            response = self.client.post('/api/knowledge/ask/stream', json={
                'question': '下一页', 'knowledge_base_id': base,
                'history': [{'question': '清华大学人才，按OpenAlex h-index降序',
                             'answer': first['answer'], 'query_state': first['query_state']}]})
        self.assertEqual(response.status_code, 200, response.text)
        events = {block.splitlines()[0][7:]: json.loads(block.splitlines()[1][6:])
                  for block in response.text.strip().split('\n\n')}
        self.assertEqual(events['meta']['query_state']['offset'], 5)
        self.assertEqual(len(events['meta']['row_sources']), 3)
        self.assertIn('第 6—8 条', events['delta']['text'])
        self.assertIn('done', events)
        model.assert_not_called()
        stream.assert_not_called()

    def test_old_conversation_requires_reestablishing_pagination(self):
        base = self.base()
        with patch.object(OpenAICompatibleProvider, 'chat') as model:
            response = self.client.post('/api/knowledge/ask', json={
                'question': '继续', 'knowledge_base_id': base,
                'history': [{'question': '清华大学人才', 'answer': '前5人'}]})
        self.assertEqual(response.status_code, 200)
        self.assertIn('旧会话没有分页记录', response.json()['answer'])
        model.assert_not_called()
