<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { request, apiFetch } from '../lib/api'
import { currentUser } from '../lib/auth'
import type { KnowledgeBase } from '../lib/types'
import AppDialog from '../components/AppDialog.vue'
const props=defineProps<{bases:KnowledgeBase[]}>()
type Row={id:string;name:string;organization:string;position:string;domain:string;location:string}
type Detail={id:string;fields:Record<string,string|null>;formulas:Record<string,string>;source_id:string;sheet_name:string;source_row:number;revision:number;indexed:boolean}
const rows=ref<Row[]>([]),total=ref(0),page=ref(1),base=ref(''),q=ref(''),org=ref(''),domain=ref(''),error=ref(''),notice=ref(''),busy=ref(false)
const detail=ref<Detail>(),history=ref<{created_at:string;fields:Record<string,string>}[]>([]),duplicates=ref<{name:string;count:number}[]>([])
function params(){return new URLSearchParams({knowledge_base_id:base.value,q:q.value,organization:org.value,domain:domain.value,page:String(page.value),page_size:'30'})}
async function load(){busy.value=true;error.value='';try{const data=await request<{items:Row[];total:number}>('/talents?'+params());rows.value=data.items;total.value=data.total}catch(e){error.value=String(e)}finally{busy.value=false}}
async function open(id:string){error.value='';try{detail.value=await request<Detail>('/talents/'+id);history.value=await request('/talents/'+id+'/history')}catch(e){error.value=String(e)}}
async function save(){if(!detail.value)return;busy.value=true;try{await request('/talents/'+detail.value.id,{method:'PUT',body:JSON.stringify({fields:detail.value.fields,revision:detail.value.revision})});detail.value=undefined;notice.value='人才信息已保存，索引更新已加入后台任务。';await load()}catch(e){error.value=String(e)}finally{busy.value=false}}
async function exportData(){try{const res=await apiFetch('/talents/export?'+params());const url=URL.createObjectURL(await res.blob());const a=document.createElement('a');a.href=url;a.download='人才列表.csv';a.click();URL.revokeObjectURL(url)}catch(e){error.value=String(e)}}
async function checkDuplicates(){try{duplicates.value=await request('/talents/duplicates');notice.value=duplicates.value.length?'同名仅表示可能重复，请核对机构和来源，系统不会自动合并。':'没有同名记录。'}catch(e){error.value=String(e)}}
onMounted(load)
</script>
<template><section class="panel talent-panel"><form class="filters" @submit.prevent="page=1;load()"><select v-model="base" aria-label="知识库"><option value="">全部可访问知识库</option><option v-for="b in props.bases" :value="b.id" :key="b.id">{{b.name}}</option></select><input v-model="q" placeholder="姓名或简介" aria-label="姓名或简介"/><input v-model="org" placeholder="机构" aria-label="机构"/><input v-model="domain" placeholder="领域" aria-label="领域"/><button class="primary" :disabled="busy">查询</button><button type="button" @click="exportData">导出结果</button><button type="button" @click="checkDuplicates">检查同名</button></form><p v-if="error" class="notice error" role="alert">{{error}}</p><p v-if="notice" class="notice">{{notice}}</p><div v-if="duplicates.length" class="tags"><button v-for="d in duplicates" :key="d.name" @click="q=d.name;page=1;load()">{{d.name}} · {{d.count}} 条</button></div><p>共 {{total}} 条人才记录</p><div class="table-wrap"><table><thead><tr><th>姓名</th><th>机构</th><th>职务</th><th>领域</th><th>地区</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td>{{row.name}}</td><td>{{row.organization}}</td><td>{{row.position}}</td><td>{{row.domain}}</td><td>{{row.location}}</td><td><button @click="open(row.id)">完整信息</button></td></tr></tbody></table></div><p v-if="!rows.length&&!busy">没有匹配的人才记录。</p><footer><button :disabled="page===1||busy" @click="page--;load()">上一页</button><span>第 {{page}} 页</span><button :disabled="page*30>=total||busy" @click="page++;load()">下一页</button></footer></section><AppDialog v-if="detail" :title="detail.fields['姓名']||'人才详情'" @close="detail=undefined"><p>来源：{{detail.sheet_name}}，第 {{detail.source_row}} 行 · {{detail.indexed?'索引已同步':'索引待同步'}}</p><p v-if="error" class="notice error">{{error}}</p><div class="talent-fields"><label v-for="(_,key) in detail.fields" :key="key"><span>{{key}}</span><textarea v-model="detail.fields[key]" :readonly="currentUser?.role==='viewer'" rows="2"/></label></div><details v-if="history.length"><summary>修改历史（{{history.length}}）</summary><details v-for="h in history" :key="h.created_at"><summary>{{h.created_at}}</summary><pre>{{h.fields}}</pre></details></details><footer><button @click="detail=undefined">关闭</button><button v-if="currentUser?.role!=='viewer'" class="primary" :disabled="busy" @click="save">保存并更新索引</button></footer></AppDialog></template>
<style scoped>.talent-panel{padding:24px}.filters{display:flex;flex-wrap:wrap;gap:10px}.filters input{width:170px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}td,th{padding:12px;text-align:left;border-bottom:1px solid #eee;max-width:240px;overflow-wrap:anywhere}footer{display:flex;gap:14px;align-items:center;justify-content:flex-end;margin-top:20px}.talent-fields{max-height:55vh;overflow:auto}.talent-fields label{display:grid;gap:6px;margin:14px 0}textarea{width:100%;min-height:60px}pre{white-space:pre-wrap}</style>
