<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {request} from '../lib/api'
import {currentUser,logout,type User} from '../lib/auth'
import type {KnowledgeBase} from '../lib/types'
const confirmPurge = () => window.confirm("彻底删除将清理不再被其他知识库使用的文件、人才及向量，是否继续？")
const emit=defineEmits<{refresh:[]}>()
const props=defineProps<{bases:KnowledgeBase[]}>()
const users=ref<User[]>([]),username=ref(''),password=ref(''),role=ref('viewer'),base=ref(''),selectedUser=ref(''),access=ref('viewer'),oldPassword=ref(''),newPassword=ref(''),error=ref(''),notice=ref('')
const orphans=ref<{id:string;filename:string}[]>([])
const operations=ref<Record<string,unknown>>({})
const trash=ref<{id:string;name:string;deleted_at:string}[]>([]),events=ref<{id:string;action:string;target:string;created_at:string}[]>([])
async function run(fn:()=>Promise<unknown>){error.value='';notice.value='';try{await fn();notice.value='操作已完成'}catch(e){error.value=String(e)}}
async function load(){if(currentUser.value?.role==='admin'){users.value=await request('/auth/users');trash.value=await request('/trash');events.value=await request('/audit');operations.value=await request('/operations');orphans.value=await request('/orphan-sources')}}
async function create(){await request('/auth/users',{method:'POST',body:JSON.stringify({username:username.value,password:password.value,role:role.value})});password.value='';await load()}
async function grant(){await request(`/auth/access/${base.value}/${selectedUser.value}?role=${access.value}`,{method:'PUT'})}
async function changePassword(){await request('/auth/password',{method:'POST',body:JSON.stringify({old_password:oldPassword.value,new_password:newPassword.value})});await logout()}
onMounted(()=>run(load))
</script>
<template><div class="team-grid"><p v-if="error" class="notice error">{{error}}</p><p v-if="notice" class="notice">{{notice}}</p><section class="panel"><h2>修改密码</h2><form @submit.prevent="run(changePassword)"><input v-model="oldPassword" type="password" autocomplete="current-password" placeholder="原密码" required/><input v-model="newPassword" type="password" autocomplete="new-password" placeholder="新密码，至少12位" minlength="12" required/><button>修改并重新登录</button></form></section><template v-if="currentUser?.role==='admin'"><section class="panel"><h2>团队账号</h2><form @submit.prevent="run(create)"><input v-model="username" placeholder="用户名" required/><input v-model="password" type="password" autocomplete="new-password" minlength="12" placeholder="初始密码，至少12位" required/><select v-model="role"><option value="viewer">只读</option><option value="editor">编辑者</option><option value="admin">管理员</option></select><button class="primary">添加账号</button></form><p v-for="u in users" :key="u.id">{{u.username}} · {{u.role}} · {{u.enabled?'启用':'停用'}} <button v-if="u.id!==currentUser.id" @click="run(async()=>{await request(`/auth/users/${u.id}/enabled?enabled=${!u.enabled}`,{method:'PUT'});await load()})">{{u.enabled?'停用':'启用'}}</button></p></section><section class="panel"><h2>知识库授权</h2><form @submit.prevent="run(grant)"><select v-model="base" required><option value="">选择知识库</option><option v-for="b in props.bases" :key="b.id" :value="b.id">{{b.name}}</option></select><select v-model="selectedUser" required><option value="">选择账号</option><option v-for="u in users" :value="u.id" :key="u.id">{{u.username}}</option></select><select v-model="access"><option value="viewer">可查看</option><option value="editor">可编辑</option><option value="none">撤销访问</option></select><button>保存权限</button></form></section><section class="panel"><h2>知识库回收站</h2><p v-if="!trash.length">回收站为空。</p><p v-for="b in trash" :key="b.id">{{b.name}} <button @click="run(async()=>{await request(`/trash/${b.id}/restore`,{method:'POST'});emit('refresh');await load()})">恢复</button><button class="danger-text" @click="run(async()=>{if(confirmPurge()){await request(`/trash/${b.id}`,{method:'DELETE'});await load()}})">彻底删除</button></p></section><section class="panel"><h2>未关联资料</h2><p>从知识库移除后保留的资料，可在此彻底清理。</p><p v-for="s in orphans" :key="s.id">{{s.filename}} <button @click="run(async()=>{if(confirmPurge()){await request(`/orphan-sources/${s.id}`,{method:'DELETE'});await load()}})">彻底删除</button></p></section><section class="panel"><h2>运行状态与备份</h2><pre>{{operations}}</pre><button @click="run(async()=>{const result=await request<{message:string}>('/operations/backup',{method:'POST'});notice=result.message})">创建完整备份</button></section><section class="panel"><h2>最近管理操作</h2><p v-for="e in events" :key="e.id">{{e.created_at}} · {{e.action}} · {{e.target}}</p></section></template></div></template>
<style scoped>.team-grid{display:grid;gap:20px}.panel{padding:24px}form{display:flex;gap:12px;flex-wrap:wrap}input{min-width:190px}</style>
